default: zip gztar

zip:
	python setup.py bdist --formats=zip

gztar:
	python setup.py bdist --formats=gztar

rpm:
	python setup.py bdist --formats=rpm

wininst:
	python setup.py bdist --formats=wininst

clean:
	rm -fr build dist